

INSERT INTO COUNTRY (ID, NAME_FR, NAME_EN) VALUES('123456789','CANADA','CANADA');
INSERT INTO COUNTRY (ID, NAME_FR, NAME_EN) VALUES('123456788','FRANCE','FRANCE');
--
INSERT INTO CITY (ID, NAME_FR, NAME_EN, COUNTRY_ID) VALUES('1', 'MONTREAL', 'MONTREAL', (SELECT id FROM COUNTRY WHERE ID = '123456789'));
INSERT INTO CITY (ID, NAME_FR, NAME_EN, COUNTRY_ID) VALUES('2', 'TORONTO', 'TORONTO', (SELECT id FROM COUNTRY WHERE ID = '123456789'));
--
INSERT INTO DISTRICT (ID, NAME_FR, NAME_EN, DESCRIPTION_FR, DESCRIPTION_EN, CITY_ID) VALUES('1','VERDUN','VERDUN','blabka','fewf', (SELECT id FROM CITY WHERE ID = '1'));