
-- Insert countries
INSERT INTO COUNTRY (ID, NAME_FR, NAME_EN) VALUES('1','CANADA','CANADA');
INSERT INTO COUNTRY (ID, NAME_FR, NAME_EN) VALUES('2','FRANCE','FRANCE');
-- Insert Cities
INSERT INTO CITY (ID, NAME_FR, NAME_EN, COUNTRY_ID) VALUES('1', 'MONTREAL', 'MONTREAL', (SELECT id FROM COUNTRY WHERE ID = '123456789'));
INSERT INTO CITY (ID, NAME_FR, NAME_EN, COUNTRY_ID) VALUES('2', 'TORONTO', 'TORONTO', (SELECT id FROM COUNTRY WHERE ID = '123456789'));
-- Insert District
INSERT INTO DISTRICT (ID, NAME_FR, NAME_EN, DESCRIPTION_FR, DESCRIPTION_EN, CITY_ID) VALUES('1','VERDUN','VERDUN','blabka','fewf', (SELECT id FROM CITY WHERE ID = '1'));

INSERT INTO POINT_OF_INTEREST (ID, NAME, ADDRESS, PHONE, URI, CATEGORY, DISTRICT_ID) VALUES('1', 'Chez Boss & Fils', '3610 Rue Wellington, Verdun', '(514)805-3457' ,'chezbossetfils.ca' , 'R', (SELECT id FROM DISTRICT WHERE ID = '1') );
INSERT INTO POINT_OF_INTEREST (ID, NAME, ADDRESS, PHONE, URI,CATEGORY, DISTRICT_ID) VALUES('2', 'Restaurant Wellington', '3629 Rue Wellington, Verdun', '(514)419-1646', 'restaurantwellington.com' , 'R', (SELECT id FROM DISTRICT WHERE ID = '1') );
INSERT INTO POINT_OF_INTEREST (ID, NAME, ADDRESS,PHONE, URI, CATEGORY, DISTRICT_ID) VALUES('3', 'Les Street Monkeys', '3625 Rue Wellington, Verdun', '(514)768-1818', 'streetmonkeys.ca' , 'R', (SELECT id FROM DISTRICT WHERE ID = '1') );
INSERT INTO POINT_OF_INTEREST (ID, NAME, ADDRESS, PHONE, URI, CATEGORY, DISTRICT_ID) VALUES('4', 'Rita', '3681 Rue Wellington, Verdun', '(514)419-1942', '' , 'R', (SELECT id FROM DISTRICT WHERE ID = '1') );
INSERT INTO POINT_OF_INTEREST (ID, NAME, ADDRESS, PHONE, URI, CATEGORY, DISTRICT_ID) VALUES('5', 'Le grill J''m la Frite', '350 Rue Strathmore, Verdun', '(514)769-3132', 'jmlafrite.com' , 'R', (SELECT id FROM DISTRICT WHERE ID = '1') );
INSERT INTO POINT_OF_INTEREST (ID, NAME, ADDRESS, PHONE, URI, CATEGORY, DISTRICT_ID) VALUES('6', 'Poutine LaFleur', '3665 Rue Wellington, Verdun', '(514)658-9071', '' , 'R', (SELECT id FROM DISTRICT WHERE ID = '1') );
INSERT INTO POINT_OF_INTEREST (ID, NAME, ADDRESS,  PHONE, URI,CATEGORY, DISTRICT_ID) VALUES('7', 'Parisa', '4123 Rue de Verdun, Verdun', '(514)768-7777', 'restaurantparisa.ca' , 'R', (SELECT id FROM DISTRICT WHERE ID = '1') );
INSERT INTO POINT_OF_INTEREST (ID, NAME, ADDRESS,  PHONE, URI,CATEGORY, DISTRICT_ID) VALUES('8', 'Pigor', '3780 Rue Wellington, Verdun', '(514)907-0816', '' , 'R', (SELECT id FROM DISTRICT WHERE ID = '1') );
INSERT INTO POINT_OF_INTEREST (ID, NAME, ADDRESS, PHONE, URI, CATEGORY, DISTRICT_ID) VALUES('9', 'La Queue de Poisson', '3779 Rue Wellington, Verdun', '(514)507-8245', '' , 'R', (SELECT id FROM DISTRICT WHERE ID = '1') );
INSERT INTO POINT_OF_INTEREST (ID, NAME, ADDRESS, PHONE, URI, CATEGORY, DISTRICT_ID) VALUES('10', 'Delhi Express', '3876 Rue Wellington, Verdun', '(514)767-6964', 'nouveau-delhi.com' , 'R', (SELECT id FROM DISTRICT WHERE ID = '1') );
